[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "lokimankeli"
version = "0.1.0"
description = "Stream JSON messages from systemd-journald to MQTT"
readme = "README.md"
requires-python = ">=3.11"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
dependencies = [
  "jq>=1.8",
  "paho-mqtt>=2.1",
  "systemd-python>=235",
]

[project.scripts]
lokimankeli = "lokimankeli.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
